/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Photo = IDL.Record({
  'id' : IDL.Text,
  'imageData' : IDL.Text,
  'timestamp' : Time,
});
export const AttemptRecord = IDL.Record({
  'codeEntered' : IDL.Text,
  'timestamp' : Time,
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  'checkUnlockCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getAttempts' : IDL.Func([], [IDL.Vec(AttemptRecord)], ['query']),
  'storePhoto' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
  'updateUnlockCode' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Photo = IDL.Record({
    'id' : IDL.Text,
    'imageData' : IDL.Text,
    'timestamp' : Time,
  });
  const AttemptRecord = IDL.Record({
    'codeEntered' : IDL.Text,
    'timestamp' : Time,
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    'checkUnlockCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getAttempts' : IDL.Func([], [IDL.Vec(AttemptRecord)], ['query']),
    'storePhoto' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
    'updateUnlockCode' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };